@endpoint=https://ohmydnd-2fd0c114d2b0.herokuapp.com

###
GET  {{ endpoint }}/api/users/1/characters

###
GET  {{ endpoint }}/api/users/1/characters/2

###
PATCH {{ endpoint }}/api/users/1/characters/2
Content-Type: application/json

{
    "name": "Florian le guerrier de l'espace",
    "armor_class": 18
}

###
DELETE {{ endpoint }}/api/users/1/characters/2

###
GET {{ endpoint }}/api/options/skills

###
POST {{ endpoint }}/api/users/1/characters/2/skills/9

###
DELETE {{ endpoint }}/api/users/3/characters/8/skills/7

###
POST {{ endpoint }}/api/users/1/characters/2/notes
Content-Type: application/json

{
    "content": "Blablabla"
}
###
DELETE {{ endpoint }}/api/users/1/characters/2/notes/1