@endpoint=https://ohmydnd-2fd0c114d2b0.herokuapp.com

POST {{ endpoint }}/api/charactercreator/creator
Content-Type: application/json

{
    "user_id": 1,
    "classe_id": 1,
    "background_id": 1,
    "race_id": 1,
    "name": "Michel le guerrier le retour",
    "level": 1,
    "strength": 20,
    "dexterity": 20,
    "constitution": 20,
    "inteligence": 20,
    "wisdom": 20,
    "charisma": 20,
    "inspiration": 20,
    "armor_class": 8,
    "alignment": "bon"
}

###
GET  {{ endpoint }}/api/charactercreator/classes


###
GET  {{ endpoint }}/api/charactercreator/races

###
GET  {{ endpoint }}/api/charactercreator/backgrounds
