@endpoint=http://localhost:{{$dotenv PORT}}

GET {{ endpoint }}/api/users/test
###


GET {{ endpoint }}/api/users/testget
###

POST {{ endpoint }}/api/users/signup
content-type: application/json

{
  "pseudo": "Nidohg",
  "email": "test@gmail.com",
  "password": "NidohgTest",
  "passwordConfirm": "NidohgTest"
}