@endpoint=http://localhost:{{$dotenv PORT}}

POST {{ endpoint }}/api/users/signin
content-type: application/json

{
  "email": "test@testgmail.com",
  "password": "NidohgTest"
}

###
POST {{ endpoint }}/api/users/signup
content-type: application/json

{
  "pseudo": "Test",
  "email": "test@testgmail.com",
  "password": "NidohgTest",
  "passwordConfirm": "NidohgTest"
}

###
DELETE {{ endpoint }}/api/users/delete
content-type: application/json

{
  "email": "test@gmail.com"
}