@endpoint=https://ohmydnd-2fd0c114d2b0.herokuapp.com

POST {{ endpoint }}/api/users/signin
content-type: application/json

{
  "email": "test@testgmail.com",
  "password": "NidohgTest"
}

###
POST {{ endpoint }}/api/users/signup
content-type: application/json

{
  "pseudo": "Test",
  "email": "test@testgmail.com",
  "password": "NidohgTest",
  "passwordConfirm": "NidohgTest"
}

###
DELETE {{ endpoint }}/api/users/4/delete
content-type: application/json

{
  "email": "test@testgmail.com"
}