@endpoint=http://localhost:{{$dotenv PORT}}

###
GET  {{ endpoint }}/api/users/3/characters

###
GET  {{ endpoint }}/api/users/4/characters/16

###
PATCH {{ endpoint }}/api/users/3/characters/8
Content-Type: application/json

{
    "name": "Florian le guerrier de l'espace",
    "armor_class": 18
}

###
DELETE {{ endpoint }}/api/users/3/characters/13

###
GET {{ endpoint }}/api/options/skills

###
POST {{ endpoint }}/api/users/3/characters/8/skills/7

###
DELETE {{ endpoint }}/api/users/3/characters/8/skills/7

###
POST {{ endpoint }}/api/users/3/characters/8/notes
Content-Type: application/json

{
    "content": "content post test"
}

###
POST {{ endpoint }}/api/users/4/characters/15/notes
Content-Type: application/json

{   
    "title": "title post test 4",
    "content": "content post test 5"
}